blogTitle = "Ross A Davis"
authorName = "Ross A Davis"
linkPrefix = "/blog"
email = "ross.ad@gmail.com"
github = "https://github.com/RossAD"
linkedin = "https://www.linkedin.com/in/rossad"
twitter = "https://twitter.com/WlshGngstr"

[navigation]
home = "/"
blog = "/blog/"
about = "/about/"
resume = "/resume/"
portfolio = "/portfolio/"
contact = "/contact/"

[about]
title = "About"
blurb = "Below is a brief summary of me, my motivations, and my pusuits."
dir = "about"

[resume]
title = "Resume"
dir = "resume"

[blog]
title = "Blog"
blurb = "This is my blog"
dir = "blog"

